trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build React Frontend
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: 'Install dependencies & build'

          - task: CopyFiles@2
            inputs:
              SourceFolder: 'frontend/build'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/frontend'
            displayName: 'Copy build artifacts'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/frontend'
              ArtifactName: 'frontend'
            displayName: 'Publish frontend artifact'

  - stage: Deploy
    displayName: Deploy React Frontend
    dependsOn: Build
    jobs:
      - deployment: DeployFrontend
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'YOUR-SERVICE-CONNECTION'
                    appName: 'your-frontend-app-service'
                    package: '$(Pipeline.Workspace)/frontend/**/*.zip'