export const BILLING_TYPE_LIST_REQUEST = 'BILLING_TYPE_LIST_REQUEST';
export const BILLING_TYPE_LIST_SUCCESS = 'BILLING_TYPE_LIST_SUCCESS';
export const BILLING_TYPE_LIST_FAIL = 'BILLING_TYPE_LIST_FAIL';

export const BILLING_TYPE_DETAILS_REQUEST = 'BILLING_TYPE_DETAILS_REQUEST';
export const BILLING_TYPE_DETAILS_SUCCESS = 'BILLING_TYPE_DETAILS_SUCCESS';
export const BILLING_TYPE_DETAILS_FAIL = 'BILLING_TYPE_DETAILS_FAIL';

export const BILLING_TYPE_CREATE_REQUEST = 'BILLING_TYPE_CREATE_REQUEST';
export const BILLING_TYPE_CREATE_SUCCESS = 'BILLING_TYPE_CREATE_SUCCESS';
export const BILLING_TYPE_CREATE_FAIL = 'BILLING_TYPE_CREATE_FAIL';
export const BILLING_TYPE_CREATE_RESET = 'BILLING_TYPE_CREATE_RESET';

export const BILLING_TYPE_UPDATE_REQUEST = 'BILLING_TYPE_UPDATE_REQUEST';
export const BILLING_TYPE_UPDATE_SUCCESS = 'BILLING_TYPE_UPDATE_SUCCESS';
export const BILLING_TYPE_UPDATE_FAIL = 'BILLING_TYPE_UPDATE_FAIL';
export const BILLING_TYPE_UPDATE_RESET = 'BILLING_TYPE_UPDATE_RESET';

export const BILLING_TYPE_DELETE_REQUEST = 'BILLING_TYPE_DELETE_REQUEST';
export const BILLING_TYPE_DELETE_SUCCESS = 'BILLING_TYPE_DELETE_SUCCESS';
export const BILLING_TYPE_DELETE_FAIL = 'BILLING_TYPE_DELETE_FAIL';
export const BILLING_TYPE_DELETE_RESET = 'BILLING_TYPE_DELETE_RESET';
