export const SEGMENT_LIST_REQUEST = 'SEGMENT_LIST_REQUEST';
export const SEGMENT_LIST_SUCCESS = 'SEGMENT_LIST_SUCCESS';
export const SEGMENT_LIST_FAIL = 'SEGMENT_LIST_FAIL';

export const SEGMENT_DETAILS_REQUEST = 'SEGMENT_DETAILS_REQUEST';
export const SEGMENT_DETAILS_SUCCESS = 'SEGMENT_DETAILS_SUCCESS';
export const SEGMENT_DETAILS_FAIL = 'SEGMENT_DETAILS_FAIL';

export const SEGMENT_CREATE_REQUEST = 'SEGMENT_CREATE_REQUEST';
export const SEGMENT_CREATE_SUCCESS = 'SEGMENT_CREATE_SUCCESS';
export const SEGMENT_CREATE_FAIL = 'SEGMENT_CREATE_FAIL';
export const SEGMENT_CREATE_RESET = 'SEGMENT_CREATE_RESET';

export const SEGMENT_UPDATE_REQUEST = 'SEGMENT_UPDATE_REQUEST';
export const SEGMENT_UPDATE_SUCCESS = 'SEGMENT_UPDATE_SUCCESS';
export const SEGMENT_UPDATE_FAIL = 'SEGMENT_UPDATE_FAIL';
export const SEGMENT_UPDATE_RESET = 'SEGMENT_UPDATE_RESET';

export const SEGMENT_DELETE_REQUEST = 'SEGMENT_DELETE_REQUEST';
export const SEGMENT_DELETE_SUCCESS = 'SEGMENT_DELETE_SUCCESS';
export const SEGMENT_DELETE_FAIL = 'SEGMENT_DELETE_FAIL';
